import { ComprehensiveApplicationData } from "@/types/application";

/**
 * Maps the comprehensive application form data onto the trainee_applications
 * table shape. Used by both staff capture and the public online application.
 */
export const buildApplicationInsert = (
  d: ComprehensiveApplicationData,
  organizationId: string,
  userId: string,
  source: "staff" | "online" = "staff"
) => ({
  first_name: d.first_name,
  last_name: d.last_name,
  date_of_birth: d.date_of_birth,
  gender: d.gender,
  national_id: d.national_id,
  phone: d.phone,
  nationality: d.nationality,
  address: d.address,
  region: d.region,
  trade_id: d.trade_id,
  trade_id_choice2: d.trade_id_choice2 || null,
  preferred_training_mode: d.preferred_training_mode,
  preferred_level: d.preferred_level,
  intake: d.intake,
  academic_year: d.academic_year,
  title: d.title || null,
  marital_status: d.marital_status || null,
  postal_address: d.postal_address || null,
  email: d.email || null,
  emergency_contact_name: d.emergency_contact_name,
  emergency_contact_phone: d.emergency_contact_phone,
  emergency_contact_relationship: d.emergency_contact_relationship,
  emergency_contact_region: d.emergency_contact_region || null,
  emergency_contact_email: d.emergency_contact_email || null,
  emergency_contact_town: d.emergency_contact_town,
  tertiary_institution: d.tertiary_institution || null,
  tertiary_region: d.tertiary_region || null,
  tertiary_address: d.tertiary_address || null,
  tertiary_phone: d.tertiary_phone || null,
  tertiary_fax: d.tertiary_fax || null,
  tertiary_exam_year: d.tertiary_exam_year || null,
  highest_grade_passed: d.highest_grade_passed,
  school_subjects: d.school_subjects as any,
  employer_name: d.employer_name || null,
  employer_address: d.employer_address || null,
  employer_phone: d.employer_phone || null,
  employer_fax: d.employer_fax || null,
  employer_town: d.employer_town || null,
  employer_region: d.employer_region || null,
  employer_position: d.employer_position || null,
  employer_duration: d.employer_duration || null,
  employer_email: d.employer_email || null,
  needs_financial_assistance: d.needs_financial_assistance,
  needs_hostel_accommodation: d.needs_hostel_accommodation,
  hostel_application_data: (d.hostel_application_data as any) || null,
  has_disability: d.has_disability,
  disability_description: d.disability_description || null,
  has_special_needs: d.has_special_needs,
  special_needs_description: d.special_needs_description || null,
  has_chronic_diseases: d.has_chronic_diseases,
  chronic_diseases_description: d.chronic_diseases_description || null,
  shoe_size: d.shoe_size || null,
  overall_size: d.overall_size || null,
  tshirt_size: d.tshirt_size || null,
  skirt_trousers_size: d.skirt_trousers_size || null,
  chef_trouser_size: d.chef_trouser_size || null,
  chef_jacket_size: d.chef_jacket_size || null,
  ict_access: d.ict_access as any,
  declaration_accepted: d.declaration_accepted,
  id_document_path: d.id_document_path || null,
  school_leaving_cert_path: d.school_leaving_cert_path || null,
  academic_qualifications_path: d.academic_qualifications_path || null,
  additional_documents_paths: (d.additional_documents_paths as any) || [],
  photo_path: d.photo_path || null,
  organization_id: organizationId,
  created_by: userId,
  application_source: source,
  application_number: `APP-${Date.now()}`,
});
