import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useOrganizationContext } from "./useOrganizationContext";
import { withOrganizationId } from "@/lib/organizationUtils";
import { isWithinLimit } from "@/lib/packageUtils";

export interface TraineeRegistrationData {
  first_name: string;
  last_name: string;
  national_id: string;
  date_of_birth: string;
  gender: "male" | "female";
  phone: string;
  email?: string;
  address: string;
  trade_id: string;
  training_mode: "fulltime" | "bdl" | "shortcourse";
  level: number;
  academic_year: string;
}

export const useRegisterTrainee = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { organizationId, packageInfo } = useOrganizationContext();

  return useMutation({
    mutationFn: async (traineeData: TraineeRegistrationData) => {
      // Check trainee limit before registration
      const { count: currentCount } = await supabase
        .from("trainees")
        .select("*", { count: "exact", head: true })
        .eq("organization_id", organizationId || "");
      
      if (!isWithinLimit(packageInfo?.limits || null, "max_trainees", currentCount || 0)) {
        throw new Error("Trainee limit reached for your package. Please upgrade to add more trainees.");
      }

      // Auto-inject organization_id using utility
      const dataWithOrg = withOrganizationId(traineeData, organizationId);

      const { data, error } = await supabase
        .from("trainees")
        .insert([{
          ...dataWithOrg,
          trainee_id: '', // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["trainees"] });
      toast({
        title: "Success",
        description: "Trainee registered successfully!",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });
};
