import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

export interface TraineeData {
  firstName: string;
  lastName: string;
  gender: string;
  dateOfBirth: string;
  national_id: string;
  phone: string;
  email?: string;
  address: string;
  trade_id: string;
  training_mode: string;
  level: number;
  academic_year: string;
}

export const useTrainees = () => {
  return useQuery({
    queryKey: ["trainees"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("trainees")
        .select(`
          *,
          trades:trade_id (
            id,
            name,
            code
          )
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data;
    },
  });
};

export const useRegisterTrainee = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (traineeData: TraineeData & { organization_id?: string }) => {
      const { data, error } = await supabase
        .from("trainees")
        .insert([{
          first_name: traineeData.firstName,
          last_name: traineeData.lastName,
          gender: traineeData.gender as "male" | "female" | "other",
          date_of_birth: traineeData.dateOfBirth,
          national_id: traineeData.national_id,
          phone: traineeData.phone,
          email: traineeData.email,
          address: traineeData.address,
          trade_id: traineeData.trade_id,
          training_mode: traineeData.training_mode as "fulltime" | "bdl" | "shortcourse",
          level: traineeData.level,
          academic_year: traineeData.academic_year,
          organization_id: traineeData.organization_id,
          trainee_id: "", // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (error) {
        // Check for duplicate national_id error
        if (error.code === '23505' && error.message.includes('national_id')) {
          throw new Error('A trainee with this National ID already exists');
        }
        throw error;
      }
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["trainees"] });
      toast({
        title: "Success",
        description: "Trainee registered successfully!",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });
};
